# Oberon discos configuration
# (DisCoS - distribution coordination server)

# server name
name: discos2

# server logging config
log:  /Users/johnl/dev/workspace/oberon/deploy/inst1/log/discos.log
log-level: DEBUG

# multicast bus connection details
bus:
    type: multicast
    group: 224.1.1.1
    port: 5007

# manhole connection
manhole:
    port: 9025
